In [2]:
import pandas as pd

x = pd.read_csv('heart.csv')

print (x)
def leer_datos(dataset):
    data = pd.read_csv(dataset) 
    x = data.iloc[:,:-1]
    y = data.iloc[:,-1]
    return x,y

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
5     57    1   0       140   192    0        1      148      0      0.4   
6     56    0   1       140   294    0        0      153      0      1.3   
7     44    1   1       120   263    0        1      173      0      0.0   
8     52    1   2       172   199    1        1      162      0      0.5   
9     57    1   2       150   168    0        1      174      0      1.6   
10    54    1   0       140   239    0        1      160      0      1.2   
11    48    0   2       130   275    0        1      139      0      0.2   
12    49    

In [14]:
from sklearn.model_selection import StratifiedKFold
csv_x, csv_y = leer_datos('heart.csv')
k_folds = []
# print (csv_.values)
kf = StratifiedKFold(n_splits=3)
kf
for train_index, test_index in kf.split(csv_x.values, csv_y.values):
    X_train, X_test, y_train, y_test = csv_x.values[train_index], csv_x.values[test_index], \
                                        csv_y.values[train_index], csv_y.values[test_index]
    print (X_train.shape, X_test.shape)
    k_folds.append(X_train)
    k_folds.append(y_train)
    k_folds.append(X_test)
    k_folds.append(y_test)
# def get_accuracy(model, X_train, y_train, X_test, y_test):

scores_mlp = []
print (X_train.shape)
# _y_train = np.asmatrix(y_train).T
print (X_test.shape)
print (y_train.shape)
print (y_test.shape)

(202, 13) (101, 13)
(202, 13) (101, 13)
(202, 13) (101, 13)
(202, 13)
(101, 13)
(202,)
(101,)


In [19]:
index = 0
for i in k_folds:
#     print (i)
    pd.DataFrame(i).to_csv('folds' + str(index) + '.csv')
    index = index + 1

[[52.  1.  1. ...  2.  1.  2.]
 [48.  1.  0. ...  2.  0.  2.]
 [45.  1.  0. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [49.  1.  2. ...  1.  3.  3.]
 [59.  1.  0. ...  2.  1.  3.]
 [57.  1.  2. ...  1.  1.  3.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [10]:
y = pd.read_csv('Iris.csv')
# print (y)
csvIris_x, csvIris_y = leer_datos('Iris.csv')
print (csvIris_x, csvIris_y.head())



     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
5              5.4           3.9            1.7           0.4
6              4.6           3.4            1.4           0.3
7              5.0           3.4            1.5           0.2
8              4.4           2.9            1.4           0.2
9              4.9           3.1            1.5           0.1
10             5.4           3.7            1.5           0.2
11             4.8           3.4            1.6           0.2
12             4.8           3.0            1.4           0.1
13             4.3           3.0            1.1           0.1
14             5.8           4.0            1.2           0.2
15      

In [24]:
from sklearn.model_selection import StratifiedKFold
k_folds_iris = []
# print (csv_.values)
kfIris = StratifiedKFold(n_splits=3)
for train_index, test_index in kfIris.split(csvIris_x.values, csvIris_y.values):
    X_train, X_test, y_train, y_test = csvIris_x.values[train_index], csvIris_x.values[test_index], \
                                        csvIris_y.values[train_index], csvIris_y.values[test_index]
#     print (X_train.shape, X_test.shape)
    print (y_train)
    k_folds_iris.append(X_train)
    k_folds_iris.append(y_train)
    k_folds_iris.append(X_test)
    k_folds_iris.append(y_test)
# def get_accuracy(model, X_train, y_train, X_test, y_test):

scores_mlp = []
print (k_folds_iris[3].shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
(51,)


In [19]:
indexIris = 0
for i in k_folds_iris:
#     print (i)
    pd.DataFrame(i).to_csv('foldsIris' + str(indexIris) + '.csv')
    indexIris = indexIris + 1

In [30]:
df = pd.read_csv('foldsIris1.csv', usecols = ['0'])
print (df)
df2 = df.join(pd.get_dummies(df.pop('0')))
print (df2)

    0
0   0
1   0
2   0
3   0
4   0
5   0
6   0
7   0
8   0
9   0
10  0
11  0
12  0
13  0
14  0
15  0
16  0
17  0
18  0
19  0
20  0
21  0
22  0
23  0
24  0
25  0
26  0
27  0
28  0
29  0
.. ..
69  2
70  2
71  2
72  2
73  2
74  2
75  2
76  2
77  2
78  2
79  2
80  2
81  2
82  2
83  2
84  2
85  2
86  2
87  2
88  2
89  2
90  2
91  2
92  2
93  2
94  2
95  2
96  2
97  2
98  2

[99 rows x 1 columns]
    0  1  2
0   1  0  0
1   1  0  0
2   1  0  0
3   1  0  0
4   1  0  0
5   1  0  0
6   1  0  0
7   1  0  0
8   1  0  0
9   1  0  0
10  1  0  0
11  1  0  0
12  1  0  0
13  1  0  0
14  1  0  0
15  1  0  0
16  1  0  0
17  1  0  0
18  1  0  0
19  1  0  0
20  1  0  0
21  1  0  0
22  1  0  0
23  1  0  0
24  1  0  0
25  1  0  0
26  1  0  0
27  1  0  0
28  1  0  0
29  1  0  0
.. .. .. ..
69  0  0  1
70  0  0  1
71  0  0  1
72  0  0  1
73  0  0  1
74  0  0  1
75  0  0  1
76  0  0  1
77  0  0  1
78  0  0  1
79  0  0  1
80  0  0  1
81  0  0  1
82  0  0  1
83  0  0  1
84  0  0  1
85  0  0  1
86  0  0  1
87  0